AWSTemplateFormatVersion: 2010-09-09
Description: This template creates a cross-account access role for a central S3 bucket.

Parameters:
  FromAccountAcronym:
    AllowedValues:
      - dyn
      - elec
      - oqs
      - qed
      - sand
      - stor
      - tran
    Description: Choose the acronym for the account that you want to access from.
    Type: String

  FromAccountId:
    Description: Account Id for the account that you want to access from.
    Type: String

  TargetBucketName:
    Description: Name of the target S3 bucket that we want to grant access to.
    Type: String

Resources:
  CrossAccountAccessRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::${FromAccountId}:root'
            Action:
              - 'sts:AssumeRole'
      MaxSessionDuration: 43200
      Path: /
      RoleName: !Join
        - '-'
        - - 'cross-account-access-role-for'  
          - !Ref FromAccountAcronym

  CrossAccountAccessPolicy:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyName: !Join
        - '-'
        - - 'cross-account-access-policy-for'  
          - !Ref FromAccountAcronym
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - 's3:ListAllMyBuckets'
            Resource: '*'
          - Effect: Allow
            Action:
              - 's3:ListBucket'
              - 's3:GetBucketLocation'
            Resource: !Sub 'arn:aws:s3:::${TargetBucketName}'
          - Effect: Allow
            Action:
              - 's3:GetObject'
              - 's3:PutObject'
              - 's3:DeleteObject'
            Resource: !Sub 'arn:aws:s3:::${TargetBucketName}/*'
      Roles:
        - !Ref CrossAccountAccessRole

Outputs:
  CrossAccountAccessRoleArn:
    Description: Cross-account access role ARN
    Value: !GetAtt CrossAccountAccessRole.Arn
